FILE:
  - REPLCAE:
      DIR: '.'
      POSIX: '/**/*.cpp'
      REGEX: [
        "CV_RGB2GRAY	cv::COLOR_RGB2GRAY",
        "CV_GRAY2RGB	cv::COLOR_GRAY2RGB",
        "CV_BGR2GRAY cv::COLOR_BGR2GRAY",
        "CV_GRAY2BGR cv::COLOR_GRAY2BGR",
        "CV_FONT_HERSHEY_SIMPLEX	cv::FONT_HERSHEY_SIMPLEX",
        "CV_LOAD_IMAGE_GRAYSCALE	cv::IMREAD_GRAYSCALE",
        "CV_MINMAX	cv::NORM_MINMAX",
        "CV_AA cv::LINE_AA",
        "CV_CALIB_CB_FILTER_QUADS cv::CALIB_CB_FILTER_QUADS",
        "CV_CALIB_CB_ADAPTIVE_THRESH cv::CALIB_CB_ADAPTIVE_THRESH",
        "CV_CALIB_CB_NORMALIZE_IMAGE cv::CALIB_CB_NORMALIZE_IMAGE",
        "CV_CALIB_CB_FAST_CHECK cv::CALIB_CB_FAST_CHECK",
        "CV_CHAIN_APPROX_SIMPLE cv::CHAIN_APPROX_SIMPLE",
        "CV_TERMCRIT_EPS cv::TermCriteria::EPS",
        "CV_TERMCRIT_ITER cv::TermCriteria::MAX_ITER",
        "CV_CALIB_CB_FILTER_QUADS cv::CALIB_CB_FILTER_QUADS",
        "CV_RETR_CCOMP cv::RETR_CCOMP",
        "CV_SHAPE_CROSS cv::MORPH_CROSS",
        "CV_SHAPE_RECT cv::MORPH_RECT",
        "CV_ADAPTIVE_THRESH_MEAN_C cv::ADAPTIVE_THRESH_MEAN_C",
        "opencv/cv.h opencv2/opencv.hpp"]
  - REPLCAE:
        DIR: '.'
        POSIX: '/**/*.cc'
        REGEX: [
          "CV_RGB2GRAY	cv::COLOR_RGB2GRAY",
          "CV_GRAY2RGB	cv::COLOR_GRAY2RGB",
          "CV_BGR2GRAY cv::COLOR_BGR2GRAY",
          "CV_GRAY2BGR cv::COLOR_GRAY2BGR",
          "CV_FONT_HERSHEY_SIMPLEX	cv::FONT_HERSHEY_SIMPLEX",
          "CV_LOAD_IMAGE_GRAYSCALE	cv::IMREAD_GRAYSCALE",
          "CV_MINMAX	cv::NORM_MINMAX",
          "CV_AA cv::LINE_AA",
          "CV_CALIB_CB_FILTER_QUADS cv::CALIB_CB_FILTER_QUADS",
          "CV_CALIB_CB_ADAPTIVE_THRESH cv::CALIB_CB_ADAPTIVE_THRESH",
          "CV_CALIB_CB_NORMALIZE_IMAGE cv::CALIB_CB_NORMALIZE_IMAGE",
          "CV_CALIB_CB_FAST_CHECK cv::CALIB_CB_FAST_CHECK",
          "CV_CHAIN_APPROX_SIMPLE cv::CHAIN_APPROX_SIMPLE",
          "CV_TERMCRIT_EPS cv::TermCriteria::EPS",
          "CV_TERMCRIT_ITER cv::TermCriteria::MAX_ITER",
          "CV_THRESH_BINARY_INV cv::THRESH_BINARY_INV",
          "CV_THRESH_BINARY cv::THRESH_BINARY",
          "CV_CALIB_CB_FILTER_QUADS cv::CALIB_CB_FILTER_QUADS",
          "CV_RETR_CCOMP cv::RETR_CCOMP",
          "CV_SHAPE_CROSS cv::MORPH_CROSS",
          "CV_SHAPE_RECT cv::MORPH_RECT",
          "CV_ADAPTIVE_THRESH_MEAN_C cv::ADAPTIVE_THRESH_MEAN_C",
          "opencv/cv.h opencv2/opencv.hpp"]
  - REPLCAE:
      DIR: '.'
      POSIX: '/**/CMakeLists.txt'
      REGEX: [
      '-std=c..11 -std=c++14',
      'VERSION.2.8.3 VERSION 3.16.0'
      ]